In [1]:
import numpy as np

# Creating arrays

In [2]:
arr = np.array((1, 2, 3, 4, 5))

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int32')

# 1D-array

In [5]:
arr1 = np.array([4, 6, 0, 8])

In [6]:
arr1

array([4, 6, 0, 8])

In [7]:
arr1[0:]

array([4, 6, 0, 8])

In [8]:
arr1[:3]

array([4, 6, 0])

In [9]:
arr1[-3:-1]

array([6, 0])

# 2D-array

In [10]:
arr2 = np.array([[1, 5, 6],[4, 7, 8]])

In [11]:
arr2[0] * arr2[1]

array([ 4, 35, 48])

In [12]:
arr2[0] + arr[1]

array([3, 7, 8])

In [13]:
arr2[1,-1]

8

In [14]:
arr2[0,0:1]

array([1])

In [15]:
arr2[0:2,2]

array([6, 8])

In [16]:
arr2[0:2, 1:4]

array([[5, 6],
       [7, 8]])

# 3D array

In [17]:
arr3 = np.array([[[1, 6, 8],[7, 8, 9]],[[5,4,7],[2, 5, 6]]])

In [18]:
arr3[0][1][0]

7

In [19]:
arr3[0][1]

array([7, 8, 9])

In [20]:
arr3.ndim

3

In [21]:
arr3[0] + arr[1]

array([[ 3,  8, 10],
       [ 9, 10, 11]])

In [22]:
arr3[0][1] * arr3[1][1]

array([14, 40, 54])

# Numpy Data Types

In [23]:
arr3.dtype

dtype('int32')

In [24]:
arrd = np.array([1, 2, 3, 4], dtype='S')

In [25]:
arrd

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [26]:
ar = np.array([1.1, 12.3, 145.6])
newar = ar.astype('i')

In [27]:
newar

array([  1,  12, 145], dtype=int32)

In [28]:
newarr = ar.astype(bool)

In [29]:
newarr

array([ True,  True,  True])

# Copy vs View

In [30]:
arr = np.array([1, 2, 3, 5, 7])
x = arr.copy()
arr[0] = 32

In [31]:
arr

array([32,  2,  3,  5,  7])

In [32]:
x

array([1, 2, 3, 5, 7])

In [33]:
arr1 = np.array([3, 7, 8, 5, 2])
y = arr1.view()
x[0] = 40

In [34]:
y

array([3, 7, 8, 5, 2])

In [35]:
arr1

array([3, 7, 8, 5, 2])

# array shape

In [36]:
arr = np.array([[1,2,4,5], [5,6,8,5]])

In [37]:
arr.shape

(2, 4)

In [38]:
arr1 = np.array([1, 2, 3, 4], ndmin=5)

In [39]:
arr1

array([[[[[1, 2, 3, 4]]]]])

In [40]:
arr1.shape

(1, 1, 1, 1, 4)

# Reshaping array

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)

In [42]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
newarr1 = arr.reshape(2,3,2)

In [45]:
newarr1 #2 arrays the contains 3 arrays each with 2 elements

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [46]:
arr.reshape(4, 3).base #this example returns the original array so it is a view

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr2 = np.array([[1, 2, 4], [9, 5, 2]])

In [48]:
#flattening array means converting a multidimensional array into a 1D array.
# we can use reshape(-1) to do this

In [49]:
newarr2 = arr2.reshape(-1)

In [50]:
newarr2

array([1, 2, 4, 9, 5, 2])

# Array Iterating

In [51]:
arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x, end=" ")

1 2 3 4 

In [52]:
for idx,z in np.ndenumerate(arr):
    print(idx,z)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [53]:
arr1 =np.array([[1, 4, 6], [6, 8, 9]])
for y in arr1:
    print(y)

[1 4 6]
[6 8 9]


In [54]:
for idx, y in np.ndenumerate(arr1):
    print(idx, y)

(0, 0) 1
(0, 1) 4
(0, 2) 6
(1, 0) 6
(1, 1) 8
(1, 2) 9


In [55]:
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for z in np.nditer(arr2):
    print(z, end=" ")

1 2 3 4 5 6 7 8 

# joining array

In [56]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([8,9,10])
newarr5 = np.concatenate((arr3, arr4))

In [57]:
newarr5

array([ 1,  2,  3,  8,  9, 10])

In [58]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2 5 6]
 [3 4 7 8]]


# Splitting Array

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


# Searching Array

In [62]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
y= np.where(arr%2 == 1)
print(y)

print(x)

(array([0, 2, 4], dtype=int64),)
(array([3, 5, 6], dtype=int64),)


In [64]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 8)

print(x)


2


In [66]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='leftside')

print(x)

1


In [68]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='rightside')

print(x)

2


# Sorting Arrays

In [70]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [72]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [74]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [76]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filter array

In [78]:
arr = np.array([41, 42, 43, 44])

x = arr[[True, False, True, False]]

print(x)

[41 43]


In [80]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


# Numpy Random

In [85]:
from numpy import random
x = random.randint(100)
print(x)

22


In [91]:
x = random.rand()

print(x)

0.72663754159697


In [97]:
x=random.randint(100, size=(5))

print(x)

[79 53  8 84 36]


In [101]:
x = random.randint(100, size=(3, 5))

print(x)


[[20 44 30  9 88]
 [23 40 86 97 34]
 [37 84  6 83 90]]
